spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/dbproject?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://127.0.0.1:3306/commenthat?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: soeo19862!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      #      ddl-auto: update
      ddl-auto: update
      naming:
        #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true



logging:
  level:
    org.hibernate.SQL: debug
    #    org.springframework.transaction: debug
    #    org.hibernate.transaction: debug
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

