spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commenthat?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dabin1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  security:
    ignored: /**
    user:
      password:
        encoder:
          enabled: true
          algorithm: sha-256
  config:
    import: applicationValue.yaml


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace